export {PortableTextEditor, keyGenerator} from './editor/PortableTextEditor'
export * from './types/editor'
export * from './types/portableText'
export * from './types/schema'
export * as StyledComponents from './editor/nodes'
export {compactPatches} from './utils/patches'
export {Patch} from './types/patch'
